config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  get "posts_on_date" => "users#posts_on_date"
  get "/search", to: "searches#search"
  get "tag_searches/search" => "tag_searches#search"
  resources :chats, only: [:show, :create, :destroy]
  
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :user_rooms
  
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
    
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end
  
  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum:50}

  
  
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end
  
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end
  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end
  
  def posts_on_date
  # リクエストの中からユーザーIDを取得し、データベースからユーザー情報を取得
  user = User.includes(:books).find(params[:user_id])

  # リクエストの中から指定された日付を取得し、日付オブジェクトに変換
  date = Date.parse(params[:created_at])

  # ユーザーが指定した日に投稿した本（books）をデータベースから検索
  @books = user.books.where(created_at: date.all_day)

  # 検索結果を表示するためのビュー（posts_on_date_form）にデータを送る
  render :posts_on_date_form
　end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.email == "guest@example.com"
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end  
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= render "relationships/btn", user: user, options: { class: "follow-link" } %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
   <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<% if user.email != "guest@example.com" %>
<div class="row">
  <%= link_to "",edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>
<% end %>

<% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
    <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
  <% end %>
　
<div class="row">
  <% if current_user != user %>
    <td><%= render "relationships/btn", user: user, options: { class: ""} %></td>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/_posts_on_date_form.html.erb
<!-- 検索フォーム部分 -->
<div class="row my-3">
  <div class="col-auto">
    <!-- フォームを生成 -->
    <%= form_with url: user_posts_on_date_path(user), method: :get, local: false do |f| %>
      <!-- 入力フィールドと送信ボタンをグループ化 -->
      <div class="input-group">
        <!-- 日付を選択する入力フィールド -->
        <%= f.date_field :created_at, class: "form-control" %>
        <!-- 送信ボタンを表示 -->
        <div class="input-group-append">
          <%= f.submit "検索", class: "btn btn-info" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- 検索結果を表示するためのコンテナ -->
<div class="posts_on_date_table mb-2">
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/posts_on_date_form.js.erb
$('.posts_on_date_table').html(`
  <h3>検索結果</h3>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
  <h2>投稿数の前日比・先週比</h2>
      <table class="table">
        <tr>
          <th>今日の投稿数</th>
          <th>前日の投稿数</th>
          <th>前日比</th>
        </tr>
        <tr>
          <td><%= @today_book.count %></td>
          <td><%= @yesterday_book.count %></td>
          <% if @yesterday_book.count == 0 %>
            <td>前日の投稿はなし</td>
          <% else %>
            <td>
              <% @the_day_before =  @today_book.count / @yesterday_book.count  %>
              <%= (@the_day_before * 100).round %>
            </td>
          <% end %>
        </tr>
      </table>

      <table class="table">
        <tr>
          <th>今週の投稿数</th>
          <th>前週の投稿数</th>
          <th>前週比</th>
        </tr>
        <tr>
          <td><%= @this_week_book.count %></td>
          <td><%= @last_week_book.count %></td>
          <% if @last_week_book.count == 0 %>
            <td>前週の投稿はなし</td>
          <% else %>
              <% @the_week_before =  @this_week_book.count / @last_week_book.count  %>
              <%= (@the_week_before * 100).round %>
          <% end %>
        </tr>
      </table>
      
      <%= render "posts_on_date_form", user: @user %>
      
      <h2>7日分の投稿数</h2>
    <table class="table table-bordered ">
      <tr>
        <th>6日前</th>
        <th>5日前</th>
        <th>4日前</th>
        <th>3日前</th>
        <th>2日前</th>
        <th>1日前</th>
        <th>今日</th>
      </tr>
      <tr>
        <td><%= @books.created_6day_ago.count %></td>
        <td><%= @books.created_5day_ago.count %></td>
        <td><%= @books.created_4day_ago.count %></td>
        <td><%= @books.created_3day_ago.count %></td>
        <td><%= @books.created_2day_ago.count %></td>
        <td><%= @books.created_yesterday.count %></td>
        <td><%= @books.created_today.count %></td>
      </tr>
    </table>
    
    <canvas id="myLineChart"></canvas>
  <script>
    $(document).on('turbolinks:load', function() {
      var ctx = document.getElementById("myLineChart");
      var myLineChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
          datasets: [
            {
              label: '投稿した本の数',
              data: [
                <%= @books.created_6day_ago.count %>,
                <%= @books.created_5day_ago.count %>,
                <%= @books.created_4day_ago.count %>,
                <%= @books.created_3day_ago.count %>,
                <%= @books.created_2day_ago.count %>,
                <%= @books.created_yesterday.count %>,
                <%= @books.created_today.count %>
              ],
              borderColor: "rgba(0,0,255,1)",
              backgroundColor: "rgba(0,0,0,0)",
              tension: 0.4
            }
          ],
        },
        options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          responsive: true,
          scales: {
            y:{
              suggestedMin: 0,
              suggestedMax: 10
            },
            x:{
              stacked: true
            },
          },
        }
      });
    });
  </script>
</div>